// <auto-generated />
using System;
using MeterDataService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeterDataService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MeterDataDbContext))]
    [Migration("20261007163605_AddReplacementTrace")]
    partial class AddReplacementTrace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeterDataService.Domain.MarketLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<string>("MaLoId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("malo_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_market_locations");

                    b.HasIndex("MaLoId")
                        .IsUnique()
                        .HasDatabaseName("ix_market_locations_malo_id");

                    b.ToTable("market_locations", (string)null);
                });

            modelBuilder.Entity("MeterDataService.Domain.MeasurementSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MeterLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_location_id");

                    b.Property<string>("ObisCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("obis_code");

                    b.HasKey("Id")
                        .HasName("pk_measurement_series");

                    b.HasIndex("MeterLocationId", "ObisCode")
                        .IsUnique()
                        .HasDatabaseName("ix_measurement_series_meter_location_id_obis_code");

                    b.ToTable("measurement_series", (string)null);
                });

            modelBuilder.Entity("MeterDataService.Domain.MeasurementValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AnchorValueAfter")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("anchor_value_after");

                    b.Property<decimal?>("AnchorValueBefore")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("anchor_value_before");

                    b.Property<DateTimeOffset>("IntervalStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("interval_start");

                    b.Property<Guid>("MeasurementSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_series_id");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("replaced_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 5)
                        .HasColumnType("numeric(18,5)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_measurement_values");

                    b.HasIndex("MeasurementSeriesId", "IntervalStart")
                        .IsUnique()
                        .HasDatabaseName("ix_measurement_values_measurement_series_id_interval_start");

                    b.ToTable("measurement_values", (string)null);
                });

            modelBuilder.Entity("MeterDataService.Domain.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("installed_at");

                    b.Property<Guid>("MeterLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("meter_location_id");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("removed_at");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_meters");

                    b.HasIndex("MeterLocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_meters_meter_location_id_active")
                        .HasFilter("removed_at IS NULL");

                    b.HasIndex("SerialNumber")
                        .HasDatabaseName("ix_meters_serial_number");

                    b.ToTable("meters", (string)null);
                });

            modelBuilder.Entity("MeterDataService.Domain.MeterLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MarketLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_location_id");

                    b.Property<string>("MeLoId")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("character(33)")
                        .HasColumnName("melo_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_meter_locations");

                    b.HasIndex("MarketLocationId")
                        .HasDatabaseName("ix_meter_locations_market_location_id");

                    b.HasIndex("MeLoId")
                        .IsUnique()
                        .HasDatabaseName("ix_meter_locations_melo_id");

                    b.ToTable("meter_locations", (string)null);
                });

            modelBuilder.Entity("MeterDataService.Domain.MeasurementSeries", b =>
                {
                    b.HasOne("MeterDataService.Domain.MeterLocation", null)
                        .WithMany("Series")
                        .HasForeignKey("MeterLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_measurement_series_meter_locations_meter_location_id");
                });

            modelBuilder.Entity("MeterDataService.Domain.MeasurementValue", b =>
                {
                    b.HasOne("MeterDataService.Domain.MeasurementSeries", null)
                        .WithMany("Values")
                        .HasForeignKey("MeasurementSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_measurement_values_measurement_series_measurement_series_id");
                });

            modelBuilder.Entity("MeterDataService.Domain.Meter", b =>
                {
                    b.HasOne("MeterDataService.Domain.MeterLocation", null)
                        .WithMany("Meters")
                        .HasForeignKey("MeterLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meters_meter_locations_meter_location_id");
                });

            modelBuilder.Entity("MeterDataService.Domain.MeterLocation", b =>
                {
                    b.HasOne("MeterDataService.Domain.MarketLocation", null)
                        .WithMany("MeterLocations")
                        .HasForeignKey("MarketLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meter_locations_market_locations_market_location_id");
                });

            modelBuilder.Entity("MeterDataService.Domain.MarketLocation", b =>
                {
                    b.Navigation("MeterLocations");
                });

            modelBuilder.Entity("MeterDataService.Domain.MeasurementSeries", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("MeterDataService.Domain.MeterLocation", b =>
                {
                    b.Navigation("Meters");

                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
